// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5N2S3D9u39Sxv0NmshHXmcuR96E_c9TE',
    appId: '1:1064385081308:web:f510673ba666ce62a0a919',
    messagingSenderId: '1064385081308',
    projectId: 'exhibition-booth-managem-be8d5',
    authDomain: 'exhibition-booth-managem-be8d5.firebaseapp.com',
    storageBucket: 'exhibition-booth-managem-be8d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhXkVL8iK2bZbCIhTfVAVxQbd4F78xq3E',
    appId: '1:1064385081308:android:9898bfa0bebfe1cda0a919',
    messagingSenderId: '1064385081308',
    projectId: 'exhibition-booth-managem-be8d5',
    storageBucket: 'exhibition-booth-managem-be8d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwmLNwXRRicoJhuxlguRPFMbTxmfkEUE8',
    appId: '1:1064385081308:ios:f74588a183ff6a25a0a919',
    messagingSenderId: '1064385081308',
    projectId: 'exhibition-booth-managem-be8d5',
    storageBucket: 'exhibition-booth-managem-be8d5.firebasestorage.app',
    iosBundleId: 'com.example.exhibitionBoothManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwmLNwXRRicoJhuxlguRPFMbTxmfkEUE8',
    appId: '1:1064385081308:ios:f74588a183ff6a25a0a919',
    messagingSenderId: '1064385081308',
    projectId: 'exhibition-booth-managem-be8d5',
    storageBucket: 'exhibition-booth-managem-be8d5.firebasestorage.app',
    iosBundleId: 'com.example.exhibitionBoothManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5N2S3D9u39Sxv0NmshHXmcuR96E_c9TE',
    appId: '1:1064385081308:web:a41c693df524e106a0a919',
    messagingSenderId: '1064385081308',
    projectId: 'exhibition-booth-managem-be8d5',
    authDomain: 'exhibition-booth-managem-be8d5.firebaseapp.com',
    storageBucket: 'exhibition-booth-managem-be8d5.firebasestorage.app',
  );

}